
# # Loads default set of integrations. Do not remove.
# default_config:

# # Load frontend themes from the themes folder
# frontend:
#   themes: !include_dir_merge_named themes

# # Text to speech
# tts:
#   - platform: google_translate

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.switch: debug
    homeassistant.components.sensor: debug


mqtt:
  - light:
    - name: "light1"
      state_topic: "homeassistant/light/status"
      command_topic: "homeassistant/light/light1/switch"
      state_value_template: "{{ value_json.light1 }}"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      
    - name: "light2"
      state_topic: "homeassistant/light/status"
      command_topic: "homeassistant/light/light2/switch"
      state_value_template: "{{ value_json.light2 }}"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  
  - lock:
    - name: "doorlock"
      state_topic: "homeassistant/doorlock/status"
      command_topic: "homeassistant/doorlock/switch"
      payload_lock: "LOCK"
      payload_unlock: "UNLOCK"
      state_locked: "LOCK"
      state_unlocked: "UNLOCK"
      



    

# Text to speech
tts:
  - platform: google_translate
  

script: !include scripts.yaml
scene: !include scenes.yaml
